export const QUOTES = [
  "The best way to predict the future is to invent it.",
  "Code is like humor. When you have to explain it, it’s bad.",
  "Security is a process, not a product.",
  "The only truly secure system is one that is powered off, cast in a block of concrete and sealed in a lead-lined room with armed guards.",
  "Programming isn't about what you know; it's about what you can figure out.",
  "The goal of a bug bounty program is not to find bugs, but to fix them.",
  "If you think technology can solve your security problems, then you don't understand the problems and you don't understand the technology.",
  "First, solve the problem. Then, write the code.",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
  "The keyboard is mightier than the sword... if you're a good programmer.",
  "Web development is not about the code you write, but the experiences you create.",
  "Amateurs hack systems, professionals hack people.",
  "There are two types of companies: those that have been hacked, and those that will be.",
  "The art of programming is the skill of controlling complexity.",
  "A bug is never just a mistake. It represents something bigger. An error of thinking that made you who you are.",
  "Software is a great combination between artistry and engineering.",
  "The best defense is a good offense, and the best offense is a good-enough defense.",
  "Cybersecurity is much more than a matter of IT.",
  "Talk is cheap. Show me the code.",
  "The measure of a programmer is not in the number of lines of code they write, but in the simplicity and elegance of their solutions.",
  "Privacy is not something that I'm merely entitled to, it's an absolute prerequisite.",
  "The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.",
  "You can't patch a human vulnerability.",
  "Good code is its own best documentation.",
  "The most dangerous vulnerability is the one you don't know about.",
  "The web is a constantly evolving ecosystem. The moment you stop learning, you start becoming obsolete.",
  "In the world of cybersecurity, the only constant is change.",
  "Building a static site is like printing a book. Building a web app is like having a conversation.",
  "A vulnerability is a gateway for threats to exploit.",
  "Simplicity is the ultimate sophistication.",
  // New 100 Quotes Below
  "To iterate is human, to recurse divine.",
  "The most secure password is the one you can’t remember.",
  "A line of code today saves ten tomorrow.",
  "Every great developer you know got there by solving problems they were unqualified to solve.",
  "The sooner you start to code, the longer the program will take.",
  "Programming is the closest thing we have to magic.",
  "The best UI is the one users don’t notice.",
  "Hackers don’t break in — they log in.",
  "If you automate a mess, you get an automated mess.",
  "Errors are opportunities in disguise.",
  "Java is to JavaScript what car is to carpet.",
  "Cybersecurity is not a product, it’s a mindset.",
  "Behind every successful app is a sleepless developer.",
  "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
  "Don’t comment bad code — rewrite it.",
  "The cloud is just someone else’s computer.",
  "The best firewalls can’t stop poor decisions.",
  "In tech, stagnation is regression.",
  "Never trust user input.",
  "Today’s hack is tomorrow’s feature.",
  "Data is the new oil, but poorly secured data is a ticking time bomb.",
  "Hacking is the art of exploring the limits.",
  "The real problem is not bugs in your code but bugs in your thinking.",
  "Software doesn't fail — it behaves unexpectedly.",
  "Great code is poetry in motion.",
  "Tech moves fast. You either keep up or fall behind.",
  "Your code reflects your thought process.",
  "Speed is important, but stability wins.",
  "Security through obscurity is not security.",
  "Don’t ship code you don’t understand.",
  "Your users don't care about your stack, only the experience.",
  "When in doubt, log everything.",
  "Complexity is the enemy of security.",
  "You learn more from broken code than perfect code.",
  "Your first version should embarrass you.",
  "A good system design saves months of debugging.",
  "Uptime is earned, not given.",
  "Don’t fear refactoring. Fear not refactoring.",
  "Your system is only as secure as your weakest link — usually, a human.",
  "If you can’t test it, don’t deploy it.",
  "Every app has bugs. The good ones just hide them better.",
  "The biggest bottleneck is usually not the code, it’s the assumptions.",
  "Think in systems, not in features.",
  "Accessibility is not optional. It’s fundamental.",
  "A good API is like a well-written story: simple, intuitive, and clear.",
  "DevOps is a culture, not a toolset.",
  "Always assume breach.",
  "Debugging is twice as hard as writing the code in the first place.",
  "Code for readability first. Performance second.",
  "Automation without understanding is just chaos on repeat.",
  "You can’t optimize what you haven’t measured.",
  "Every commit is a contract with your future self.",
  "The longer the comment, the worse the code.",
  "Open source is about people, not just code.",
  "Latency is the silent killer of UX.",
  "Code reviews are about improvement, not ego.",
  "Never deploy on Friday.",
  "Security is everyone's responsibility.",
  "Every framework is a trade-off.",
  "Make it work, make it right, then make it fast.",
  "Scalability begins with simplicity.",
  "Documentation is part of the product.",
  "Great developers write less code, not more.",
  "A compiler is just a really mean code reviewer.",
  "Know your users, not just your use cases.",
  "Never underestimate the power of a well-named variable.",
  "Most outages are self-inflicted.",
  "In code, clarity beats cleverness.",
  "All technology ages — plan for it.",
  "If your code needs a manual, you failed at UX.",
  "Fail fast, recover faster.",
  "Infrastructure as code is infrastructure you can trust.",
  "The easiest code to secure is the code you don’t write.",
  "Don't write code to solve problems you don't yet have.",
  "Not all tech debt is bad — some is strategic.",
  "Performance is a feature, not an afterthought.",
  "Being a developer means being comfortable with being wrong — often.",
  "No logs, no visibility. No visibility, no control.",
  "Minimalism in code reflects maximal thought.",
  "A well-structured codebase scales teams, not just products.",
  "Trust is earned through transparency.",
  "Good design is invisible.",
  "Test early, test often, test automatically.",
  "Keep your dependencies few and your assumptions fewer.",
  "Deploy what you can roll back.",
  "Backups don’t matter. Restores do.",
  "Don’t chase shiny tech. Solve real problems.",
  "Dev tools don’t make you better. Practice does.",
  "Technology fails. Resilience succeeds.",
  "The best product decisions are backed by data and empathy.",
  "You don’t need 100% test coverage. You need meaningful test coverage.",
  "Never build something you wouldn’t want to maintain.",
  "Ugliness is forgiven. Downtime is not.",
  "Security isn’t a checklist — it’s a culture.",
  "Great software feels obvious in hindsight.",
  "All code is technical debt until proven otherwise.",
  "An ounce of planning is worth a pound of debugging.",
  "Your best feature is reliability.",
  "Not everything needs to scale — some things just need to work.",
  "Complexity breeds confusion. Simplicity breeds confidence.",
  "No system is perfect — only less broken.",
  "Technology is built by humans, and thus, as fallible as them."
];
