
export const QUOTES = [
  "The best way to predict the future is to invent it.",
  "Code is like humor. When you have to explain it, it’s bad.",
  "Security is a process, not a product.",
  "The only truly secure system is one that is powered off, cast in a block of concrete and sealed in a lead-lined room with armed guards.",
  "Programming isn't about what you know; it's about what you can figure out.",
  "The goal of a bug bounty program is not to find bugs, but to fix them.",
  "If you think technology can solve your security problems, then you don't understand the problems and you don't understand the technology.",
  "First, solve the problem. Then, write the code.",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
  "The keyboard is mightier than the sword... if you're a good programmer.",
  "Web development is not about the code you write, but the experiences you create.",
  "Amateurs hack systems, professionals hack people.",
  "There are two types of companies: those that have been hacked, and those that will be.",
  "The art of programming is the skill of controlling complexity.",
  "A bug is never just a mistake. It represents something bigger. An error of thinking that made you who you are.",
  "Software is a great combination between artistry and engineering.",
  "The best defense is a good offense, and the best offense is a good-enough defense.",
  "Cybersecurity is much more than a matter of IT.",
  "Talk is cheap. Show me the code.",
  "The measure of a programmer is not in the number of lines of code they write, but in the simplicity and elegance of their solutions.",
  "Privacy is not something that I'm merely entitled to, it's an absolute prerequisite.",
  "The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.",
  "You can't patch a human vulnerability.",
  "Good code is its own best documentation.",
  "The most dangerous vulnerability is the one you don't know about.",
  "The web is a constantly evolving ecosystem. The moment you stop learning, you start becoming obsolete.",
  "In the world of cybersecurity, the only constant is change.",
  "Building a static site is like printing a book. Building a web app is like having a conversation.",
  "A vulnerability is a gateway for threats to exploit.",
  "Simplicity is the ultimate sophistication.",
];
